#!/usr/bin/env ruby

$: << "#{File.dirname(__FILE__)}/lib"

require 'client_connection'

# TODO: Specify this on the command line
WODA_PORT = 4242

EventMachine::run do
  host = '0.0.0.0'
  port = WODA_PORT
  EventMachine::start_server host, port, ClientConnection
end
