#!/usr/bin/env ruby

$: << "#{File.dirname(__FILE__)}/lib"

require 'environment'
require 'connection/client_connection'
require 'optparse'

woda_port = 8850
use_tls = true
OptionParser.new do |opts|
  opts.banner = "Usage: #{opts.program_name}"

  opts.on("-p", "--port PORT", "Listen to the following PORT") do |port|
    woda_port = port.to_i
  end

  opts.on("-s", "--[no-]ssl", "--[no-]tls", "Use a TLS connection (default)") do |b|
    use_tls = b
  end
end.parse!

puts "Starting server"

EventMachine::run do
  host = '0.0.0.0'
  port = woda_port
  EventMachine::start_server host, port, (use_tls ? ClientSslConnection : ClientConnection)
end
