# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'simplecov'

SimpleCov.start

require 'pathname'

def require_corresponding file
  path = Pathname(file).relative_path_from(Pathname.new(File.expand_path("..", __FILE__))).to_s
  path = path.split("/")[1..-1]
  path[-1].gsub!(/_spec.rb$/, ".rb")
  path = path.join '/'
  path = File.expand_path("../../lib/#{path}", __FILE__)
  require path
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
