#!/bin/bash

cd $(dirname `perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`)

if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi
if [ -x tracked/$(basename $0) ]; then
    tracked/$(basename $0) "$@" || exit $?
fi
