#!/usr/bin/env ruby

require File.expand_path "../../lib/environment", __FILE__

name = ARGV[0]

if name.nil?
  puts "Need to specify a migration name"
  exit
end

begin
  Dir.mkdir "#{Server.root}/ks/"
  Dir.mkdir "#{Server.root}/ks/migrate/"
rescue Exception
end

timestamp = Time.now.utc.strftime("%Y%m%d%H%M%S")

File.open("#{Server.root}/ks/migrate/#{timestamp}_#{name.underscore}.rb", "w") do |f|
  f.write <<EOS
class #{name.classify} < ActiveColumn::Migration

  def self.up

  end

  def self.down

  end

end
EOS
end
